// <auto-generated />
namespace MVC_Web_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class bp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bp));
        
        string IMigrationMetadata.Id
        {
            get { return "202202220507228_bp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
